table:
  name: Sensor_Values
  schema: public
object_relationships:
- name: Sensor
  using:
    foreign_key_constraint_on: SensorID
select_permissions:
- permission:
    columns:
    - SensorID
    - Timestamp
    - Value
    - id
    filter: {}
  role: user
